version: '3.8'

services:
  spark:
    image: apache/spark:3.4.1
    container_name: spark
    environment:
      - SPARK_MODE=client
    volumes:
      - ./:/app
    networks:
      - bda-network
    ports:
      - "4040:4040"   # Spark UI
    command: sleep infinity

networks:
  bda-network:
    external: true
