version: '3.8'

services:
  spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=client
    volumes:
      - ./:/app
    networks:
      - bda-network
    command: sleep infinity

networks:
  bda-network:
    external: true
