services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=bda-hdfs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"   # NameNode UI
      - "8020:8020"   # HDFS RPC
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - bda-network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=bda-hdfs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"   # DataNode UI
    depends_on:
      - namenode
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - bda-network

volumes:
  namenode_data:
  datanode_data:

networks:
  bda-network:
    external: true
